config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root controller: 'home', action: 'index'

  get "/about", controller: 'home', action: 'about', as: 'about'
  get "/contact", controller: 'home', action: 'contact', as: 'contact'
  get "/admin", controller: 'admincontroller', action: 'index', as: 'index'


end

app/models/calory.rb
class Calory < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
belongs_to :category    
validates :title, :ingredients, :instructions, presence: true


  def self.find_all_by_query(query)
    query = query.downcase
    query = "%#{query}%"
 
    Recipe.where(['lower(title) like ?
                   OR lower(ingredients) like ?
                   OR lower(instructions) like ?',
                   query, query, query])
  end
end

app/models/recipe_test.rb
require 'test_helper'
class RecipeTest < ActiveSupport::TestCase
 test "creates a valid record" do
 recipe = Recipe.new
 recipe.title = "Ice water"
 recipe.ingredients = ["one glass","water","ice"].join("<br>")
 recipe.instructions = "Combine all ingredients into the glass and let sit for
 two minutes. Serve immediately."
 assert recipe.save
 end
 test "should not save unless title is filled in" do
 recipe = Recipe.new
 assert !recipe.save # save should fail because there are errors.
 assert recipe.errors[:title].include?("can't be blank")
 end
 test "should not save unless ingredients is filled in" do
 recipe = Recipe.new
 assert !recipe.save # save should fail because there are errors.
 assert recipe.errors[:ingredients].include?("can't be blank")
 end
 test "should not save unless instructions is filled in" do
 recipe = Recipe.new
 assert !recipe.save # save should fail because there are errors.
 assert recipe.errors[:instructions].include?("can't be blank")
 end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  def self.authenticate(username, password)
    user = User.where(username: username).first
    user && user.authenticate(password)
  end

end

app/controllers/admincontroller_controller.rb
class AdmincontrollerController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_title
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  
  def set_title
    @title = " Cookbook"
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :logged_in?
  
  def logged_in?
    session[:logged_in]
  end
  
private

  def authenticate
    if user = authenticate_with_http_basic {|user, password| User.authenticate(user, password)}
        session[:user_id] = user.id
        session[:logged_in] = true
      else
        request_http_basic_authentication
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @number_of_recipes = Recipe.count
    @latest_recipe = Recipe.last
  end

  def about
  end
  
  def contact
    @phone = "1.800.EAT.FOOD"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :except => [:index, :show]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:q]
      @recipes = Recipe.find_all_by_query(params[:q])
    else
      @recipes = Recipe.all
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @categories = Category.all.collect{|c| [c.name, c.id] }
    @calories = Calory.all.collect{|c| [c.name, c.id] }
  end

  # GET /recipes/1/edit
  def edit
    @categories = Category.all.collect{|c| [c.name, c.id] }
    @calories = Calory.all.collect{|c| [c.name, c.id] }
  end

  # POST /recipes
  # POST /recipes.json
def create
 @recipe = Recipe.new(recipe_params)
 if @recipe.save
 redirect_to @recipe, notice: 'Recipe was successfully created.'
 else
 render :new
 end
end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.includes(:category).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :instructions, :category_id, :calory_id)
    end
end

app/helpers/admincontroller_helper.rb
module AdmincontrollerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/admincontroller/index.html.erb
<h1>You Are Logged In!<h1>

app/views/home/about.html.erb
<h2>About</h2>
<p>This is a simple cookbook application I wrote. I hope you like it.</p>

app/views/home/contact.html.erb
<h2>Contact Us</h2>
<p>Contact us at <%= @phone %></p>

app/views/home/index.html.erb
<h3>Latest Recipe</h3>
  <% if @latest_recipe %>
    <h4><%=@latest_recipe.title %></h4>
    <p><%=@latest_recipe.ingredients %></p>
    <p><%=@latest_recipe.instructions %></p>
  <% else %>
    <p>There are no recipes to display</p>
<% end %>

<%= render "/shared/search" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
 <title><%= @title %></title>
 <%= csrf_meta_tags %>

 </head>
 <body>
 <div class="container">
 <header>
 <h1>Our Cookbook</h1>
 </header>
 
<nav>
 <%= link_to_unless_current 'Home', root_url %>
 <%= link_to_unless_current 'Recipes', recipes_url %>
 <%= link_to_unless_current 'About', about_url %>
</nav>

 
 <main class="content">
 <%= yield %>
 </main>
 <footer>
 <h4>Copyright <%=Date.today.year %> OurCookbook</h4>
 </footer>
 </div>
 </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :calory_id %><br />
    <%= f.select :calory_id, @calories, :include_blank => true %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render "/shared/search" %>
<h1>Listing recipes</h1>
<table>
 <tr>
  
 <% if logged_in? %>
 You are logged in as <%= current_user.username %>
 <% end %>
  
 <th>Title</th>
 <th>Category</th>
 <th>Last Updated</th>
 <th colspan="2">&nbsp;</th>
 </tr>
 <% @recipes.each do |recipe| %>
 <tr>
 <td><%= link_to recipe.title, recipe %></td>
 <td><%= recipe.category.name rescue "No category" %></td>
 <td><%= time_ago_in_words(recipe.updated_at) %> ago</td>
 <td>
 <% if logged_in? %>
 <%= link_to 'Edit', edit_recipe_path(recipe) %>
 <% end %>
 </td>
 <td>
 <% if logged_in? %>
 <%= button_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %>
 <% end %>
 </td>
 </tr>
 <% end %>
</table>
<% if logged_in? %>
<%= link_to 'New Recipe', new_recipe_path %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<article>
 <header>
 <h2>
 <%= @recipe.title %>
 <% if logged_in? %>
 [ <%= link_to 'Edit', edit_recipe_path(@recipe) %> ]
 <% end %>
 </h2>
 </header>
 <h3>Ingredients:</h3>
 <p><%= @recipe.ingredients %></p>
 <h3>Instructions</h3>
 <p><%= @recipe.instructions %></p>
 <p>Category: <%= h(@recipe.category.name) rescue 'No category found' %></p>
</article>
<p><%= link_to 'Back', recipes_path %></p>

app/views/shared/_search.html.erb
<%= form_tag recipes_url, method: :get do %>
 <label for="query">Keywords: </label>
 <input type="search" id="query" name="q" value="<%= params[:q] %>">
 <input type="submit" value="Search">
<% end %>